server:
  port: 8081

spring:
  datasource:
    url:  jdbc:mariadb://localhost:3306/portal?&useSSL=false
    password: dev
    username: dev
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
