server:
  port: 8085 
spring:
  main.web-application-type: reactive
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://192.168.1.108:3306/portal
    password: dev
    username: dev
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    
